### ISSUE TITLE
Tests fail with non-English locale (MooX-Options-4.019)

### ISSUE THREAD

**Issue by eserte** [celogeek/MooX-Options#44]
With a German locale:
```
#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 54.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'

#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 60.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'
# Looks like you failed 2 tests of 6.
t/around_options_usage.t ................. 
...
#   Failed test 'negativable and format are incompatible'
#   at t/failure.t line 37.
#                   'Ung"ultige Formatspezifikation. Negierbare Parameter sind mit Bool'schen Werten nicht einsetzbar. at (eval 6) line 5.
# '
#     doesn't match '(?^x:^Negativable\sparams\sis\snot\susable\swith\snon\sboolean\svalue,\sdon't\spass\sformat\sto\suse\sit\s\!)'

... (etc.) ...
```

**Comment by celogeek** [comment]
Oh yes. They is the translation. I need to force the locale in the tests.

**Comment by celogeek** [comment]
fixed in 4.020

**Comment by eserte** [comment]
Unfortunately I still see failures in 4.020 with German locale. Somehow the setlocale calls have no effect. I'll investigate a little bit.

**Comment by eserte** [comment]
... I mean setting `$ENV{LC_ALL}`, `setlocale` is gone in the new version.

**Comment by celogeek** [comment]
i have regroup this env in t::Test

can you give me you locale ?

**Comment by celogeek** [comment]
i have try with :

LANG=de_DE prove -lr t

**Comment by eserte** [comment]
Strange, there seem to be a difference if I use `perl` directly or `prove`:
```
$ ./Build 
Building MooX-Options
$ env LANG=de_DE /opt/perl-5.20.3/bin/perl -Mblib t/around_options_usage.t 
ok 1 - Pre message ok
not ok 2 - Usage ok
#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 46.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'
ok 3 - Post message ok
ok 4 - Pre message ok
not ok 5 - Usage ok
#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 52.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'
ok 6 - Post message ok
1..6
# Looks like you failed 2 tests of 6.
$ env LANG=de_DE /opt/perl-5.20.3/bin/perl -Ilib t/around_options_usage.t  
ok 1 - Pre message ok
ok 2 - Usage ok
ok 3 - Post message ok
ok 4 - Pre message ok
ok 5 - Usage ok
ok 6 - Post message ok
1..6
```
I think it should also fail on your system if you try `LANG=de_DE ./Build test`.

**Comment by eserte** [comment]
OK, easy explanation: `prove -l` does load share/dist/MooX-Options/LocaleData/*. But with `prove -b` (after running `Build`) you should see the failure, too.

**Comment by celogeek** [comment]
I have test several thing :

```
dzil build
cd MooX-Options-4.020
```

then

```
LANG=de_DE ./Build test
t/00-compile.t ........................... ok   
t/000-report-versions.t .................. # Testing with Perl 5.022000, /Users/celogeek/perl5/perlbrew/perls/perl-5.22.0/bin/perl
t/000-report-versions.t .................. 1/? #     Capture::Tiny version is 0.30
#     Carp version is 1.36
#     Data::Record version is 0.02
#     English version is 1.09
#     File::Spec version is 3.56
#     FindBin version is 1.51
#     Getopt::Long version is 2.47
#     Getopt::Long::Descriptive version is 0.099
#     IO::Handle version is 1.35
#     IPC::Open3 version is 1.18
#     Import::Into version is 1.002005
#     JSON::MaybeXS version is 1.003005
#     Locale::TextDomain version is 1.24
#     Module::Build version is 0.4214
#     Module::Metadata version is 1.000027
#     Moo version is 2.000002
#     MooX::ConfigFromFile version is 0.007
#     Path::Class version is 0.35
#     Pod::Usage version is 1.67
#     Regexp::Common version is 2013031301
#     Role::Tiny::With version is 2.000001
#     Scalar::Util version is 1.42
#     Term::Size::Any version is 0.002
#     Test::More version is 1.001014
#     Test::Requires version is 0.10
#     Test::Trap version is 0.3.2
#     Text::LineFold version is 2012.04
#     Try::Tiny version is 0.22
#     blib version is 1.06
#     feature version is 1.40
#     lib version is 0.63
#     namespace::clean version is 0.26
#     overload version is 1.26
#     parent version is 0.234
#     strict version is 1.09
#     warnings version is 1.32
t/000-report-versions.t .................. ok    
t/around_options_usage.t ................. ok   
t/author-critic.t ........................ skipped: these tests are for testing by the author
t/author-pod-coverage.t .................. skipped: these tests are for testing by the author
t/autosplit_warning_on_required_param.t .. ok   
t/check_target_methods.t ................. ok   
t/doc-utf8.t ............................. ok   
t/doc.t .................................. ok   
t/failure.t .............................. ok    
t/flavour.t .............................. ok   
t/hidden.t ............................... ok   
t/isa_check.t ............................ ok   
t/mo.t ................................... ok   
t/moo.t .................................. ok   
t/moose.t ................................ ok   
t/moox-cmd.t ............................. ok    
t/multi_role.t ........................... ok   
t/multiple-split-options.t ............... ok   
t/namespace_clean.t ...................... ok   
t/no_option.t ............................ ok   
t/option-of-option.t ..................... ok   
t/order.t ................................ ok   
t/pod.t .................................. skipped: these tests are for release candidate testing
t/release-kwalitee.t ..................... skipped: these tests are for release candidate testing
t/release-unused-vars.t .................. skipped: these tests are for release candidate testing
t/role.t ................................. ok   
t/spacer.t ............................... ok    
t/string_with_zero_value.t ............... ok   
t/usage_string.t ......................... ok   
t/with_config.t .......................... ok    
All tests successful.
Files=31, Tests=156,  5 wallclock secs ( 0.19 usr  0.07 sys +  4.78 cusr  0.55 csys =  5.59 CPU)
Result: PASS
```

and

```
LANG=de_DE perl -Ilib t/around_options_usage.t 
ok 1 - Pre message ok
ok 2 - Usage ok
ok 3 - Post message ok
ok 4 - Pre message ok
ok 5 - Usage ok
ok 6 - Post message ok
1..6
```

No error. This is strange. I have error before my patch. Are you sure to be up to date with 4.020 devel branch ?

**Comment by eserte** [comment]
It's the current version from CPAN:
```
$ pwd
/home/eserte/.cpan/build/2015110815/MooX-Options-4.020-2U_dRl
```

**Comment by celogeek** [comment]
Here with the version on CPAN :

```
LANG=de_DE cpanm -v https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
cpanm (App::cpanminus) 1.7039 on perl 5.022000 built for darwin-2level
Work directory is /Users/celogeek/.cpanm/work/1447007975.46834
You have make /usr/bin/make
You have LWP 6.13
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
--> Working on https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
Fetching https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz ... OK
Unpacking MooX-Options-4.020.tar.gz
x MooX-Options-4.020/t
x MooX-Options-4.020/t/mo.t
x MooX-Options-4.020
x MooX-Options-4.020/README
x MooX-Options-4.020/Changes
x MooX-Options-4.020/t/doc.t
x MooX-Options-4.020/t/moo.t
x MooX-Options-4.020/t/pod.t
x MooX-Options-4.020/LICENSE
x MooX-Options-4.020/dist.ini
x MooX-Options-4.020/po
x MooX-Options-4.020/po/de.po
x MooX-Options-4.020/t/role.t
x MooX-Options-4.020/META.yml
x MooX-Options-4.020/MANIFEST
x MooX-Options-4.020/Build.PL
x MooX-Options-4.020/t/base.st
x MooX-Options-4.020/t/moose.t
x MooX-Options-4.020/t/order.t
x MooX-Options-4.020/t/Test.pm
x MooX-Options-4.020/META.json
x MooX-Options-4.020/t/hidden.t
x MooX-Options-4.020/t/spacer.t
x MooX-Options-4.020/README.mkdn
x MooX-Options-4.020/po/de_DE.po
x MooX-Options-4.020/t/failure.t
x MooX-Options-4.020/t/flavour.t
x MooX-Options-4.020/coverage.txt
x MooX-Options-4.020/t/doc-utf8.t
x MooX-Options-4.020/t/moox-cmd.t
x MooX-Options-4.020/t/isa_check.t
x MooX-Options-4.020/t/no_option.t
x MooX-Options-4.020/t/multi_role.t
x MooX-Options-4.020/xt
x MooX-Options-4.020/xt/perltidy.rc
x MooX-Options-4.020/t/00-compile.t
x MooX-Options-4.020/t/with_config.t
x MooX-Options-4.020/t/usage_string.t
x MooX-Options-4.020/xt/perlcritic.rc
x MooX-Options-4.020/t/author-critic.t
x MooX-Options-4.020/lib/MooX
x MooX-Options-4.020/lib/MooX/Options.pm
x MooX-Options-4.020/po/MooX-Options.pot
x MooX-Options-4.020/t/namespace_clean.t
x MooX-Options-4.020/t/option-of-option.t
x MooX-Options-4.020/t/lib
x MooX-Options-4.020/t/lib/MooXCmdTest.pm
x MooX-Options-4.020/t/release-kwalitee.t
x MooX-Options-4.020/etc
x MooX-Options-4.020/etc/with_config.t.json
x MooX-Options-4.020/t/000-report-versions.t
x MooX-Options-4.020/t/release-unused-vars.t
x MooX-Options-4.020/t/author-pod-coverage.t
x MooX-Options-4.020/etc/with_config_2.t.json
x MooX-Options-4.020/lib/MooX/Options
x MooX-Options-4.020/lib/MooX/Options/Role.pm
x MooX-Options-4.020/t/around_options_usage.t
x MooX-Options-4.020/t/check_target_methods.t
x MooX-Options-4.020/t/multiple-split-options.t
x MooX-Options-4.020/t/string_with_zero_value.t
x MooX-Options-4.020/t/lib/TestNamespaceClean.pm
x MooX-Options-4.020/t/lib/MooXCmdTest/Cmd
x MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1.pm
x MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test3.pm
x MooX-Options-4.020/lib/MooX/Options/Descriptive.pm
x MooX-Options-4.020/lib/MooX/Options/Manual
x MooX-Options-4.020/lib/MooX/Options/Manual/Man.pod
x MooX-Options-4.020/lib/MooX/Options/Manual/MooXCmd.pod
x MooX-Options-4.020/lib/MooX/Options/Descriptive
x MooX-Options-4.020/lib/MooX/Options/Descriptive/Usage.pm
x MooX-Options-4.020/t/autosplit_warning_on_required_param.t
x MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1/Cmd
x MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1/Cmd/test2.pm
x MooX-Options-4.020/lib/MooX/Options/Manual/NamespaceClean.pod
x MooX-Options-4.020/share/LocaleData/de/LC_MESSAGES
x MooX-Options-4.020/share/LocaleData/de/LC_MESSAGES/MooX-Options.mo
x MooX-Options-4.020/share/LocaleData/de_DE/LC_MESSAGES
x MooX-Options-4.020/share/LocaleData/de_DE/LC_MESSAGES/MooX-Options.mo
Entering MooX-Options-4.020
Checking configure dependencies from META.json
Checking if you have Module::Build 0.4211 ... Yes (0.4214)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.04)
Running Build.PL
Configuring MooX-Options-4.020 ... Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'MooX-Options' version '4.020'
OK
Checking dependencies from MYMETA.json ...
Checking if you have MooX::ConfigFromFile 0 ... Yes (0.007)
Checking if you have lib 0 ... Yes (0.63)
Checking if you have parent 0 ... Yes (0.234)
Checking if you have Term::Size::Any 0 ... Yes (0.002)
Checking if you have JSON::MaybeXS 0 ... Yes (1.003005)
Checking if you have namespace::clean 0 ... Yes (0.26)
Checking if you have feature 0 ... Yes (1.40)
Checking if you have FindBin 0 ... Yes (1.51)
Checking if you have Path::Class 0.32 ... Yes (0.35)
Checking if you have Text::LineFold 0 ... Yes (2012.04)
Checking if you have strict 0 ... Yes (1.09)
Checking if you have Test::Trap 0 ... Yes (0.3.2)
Checking if you have Carp 0 ... Yes (1.36)
Checking if you have Try::Tiny 0 ... Yes (0.22)
Checking if you have IPC::Open3 0 ... Yes (1.18)
Checking if you have Capture::Tiny 0 ... Yes (0.30)
Checking if you have Locale::TextDomain 0 ... Yes (1.24)
Checking if you have File::Spec 0 ... Yes (3.56)
Checking if you have overload 0 ... Yes (1.26)
Checking if you have Getopt::Long::Descriptive 0.099 ... Yes (0.099)
Checking if you have File::ShareDir 1.00 ... Yes (1.102)
Checking if you have Module::Metadata 1.000019 ... Yes (1.000027)
Checking if you have Role::Tiny::With 0 ... Yes (2.000001)
Checking if you have Moo 1.003001 ... Yes (2.000002)
Checking if you have Module::Build 0.4211 ... Yes (0.4214)
Checking if you have Getopt::Long 2.43 ... Yes (2.47)
Checking if you have English 0 ... Yes (1.09)
Checking if you have blib 1.01 ... Yes (1.06)
Checking if you have warnings 0 ... Yes (1.32)
Checking if you have Regexp::Common 0 ... Yes (2013031301)
Checking if you have Data::Record 0 ... Yes (0.02)
Checking if you have Test::Requires 0 ... Yes (0.10)
Checking if you have Pod::Usage 0 ... Yes (1.67)
Checking if you have Test::More 0.94 ... Yes (1.001014)
Checking if you have Import::Into 0 ... Yes (1.002005)
Checking if you have IO::Handle 0 ... Yes (1.35)
Checking if you have Scalar::Util 0 ... Yes (1.42)
Building and testing MooX-Options-4.020 ... Building MooX-Options
t/00-compile.t ........................... ok   
t/000-report-versions.t .................. # Testing with Perl 5.022000, /Users/celogeek/perl5/perlbrew/perls/perl-5.22.0/bin/perl
t/000-report-versions.t .................. 1/? #     Capture::Tiny version is 0.30
#     Carp version is 1.36
#     Data::Record version is 0.02
#     English version is 1.09
#     File::Spec version is 3.56
#     FindBin version is 1.51
#     Getopt::Long version is 2.47
#     Getopt::Long::Descriptive version is 0.099
#     IO::Handle version is 1.35
#     IPC::Open3 version is 1.18
#     Import::Into version is 1.002005
#     JSON::MaybeXS version is 1.003005
#     Locale::TextDomain version is 1.24
#     Module::Build version is 0.4214
#     Module::Metadata version is 1.000027
#     Moo version is 2.000002
#     MooX::ConfigFromFile version is 0.007
#     Path::Class version is 0.35
#     Pod::Usage version is 1.67
#     Regexp::Common version is 2013031301
#     Role::Tiny::With version is 2.000001
#     Scalar::Util version is 1.42
#     Term::Size::Any version is 0.002
#     Test::More version is 1.001014
#     Test::Requires version is 0.10
#     Test::Trap version is 0.3.2
#     Text::LineFold version is 2012.04
#     Try::Tiny version is 0.22
#     blib version is 1.06
#     feature version is 1.40
#     lib version is 0.63
#     namespace::clean version is 0.26
#     overload version is 1.26
#     parent version is 0.234
#     strict version is 1.09
#     warnings version is 1.32
t/000-report-versions.t .................. ok    
t/around_options_usage.t ................. ok   
t/author-critic.t ........................ skipped: these tests are for testing by the author
t/author-pod-coverage.t .................. skipped: these tests are for testing by the author
t/autosplit_warning_on_required_param.t .. ok   
t/check_target_methods.t ................. ok   
t/doc-utf8.t ............................. ok   
t/doc.t .................................. ok   
t/failure.t .............................. ok    
t/flavour.t .............................. ok   
t/hidden.t ............................... ok   
t/isa_check.t ............................ ok   
t/mo.t ................................... ok   
t/moo.t .................................. ok   
t/moose.t ................................ ok   
t/moox-cmd.t ............................. ok    
t/multi_role.t ........................... ok   
t/multiple-split-options.t ............... ok   
t/namespace_clean.t ...................... ok   
t/no_option.t ............................ ok   
t/option-of-option.t ..................... ok   
t/order.t ................................ ok   
t/pod.t .................................. skipped: these tests are for release candidate testing
t/release-kwalitee.t ..................... skipped: these tests are for release candidate testing
t/release-unused-vars.t .................. skipped: these tests are for release candidate testing
t/role.t ................................. ok   
t/spacer.t ............................... ok    
t/string_with_zero_value.t ............... ok   
t/usage_string.t ......................... ok   
t/with_config.t .......................... ok    
All tests successful.
Files=31, Tests=156,  6 wallclock secs ( 0.19 usr  0.09 sys +  4.84 cusr  0.57 csys =  5.69 CPU)
Result: PASS
Building MooX-Options
OK
Successfully installed MooX-Options-4.020
Installing /Users/celogeek/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/darwin-2level/.meta/MooX-Options-4.020/install.json
1 distribution installed
```

I try on BSD to check

**Comment by eserte** [comment]
... and I see the error also with the git version (commit 78f1ab258348f72af01ba4573266d0b32da65a9a) when running `LANG=de_DE /opt/perl-5.20.3/bin/dzil test`

This is on linux (Debian wheezy).

**Comment by celogeek** [comment]
Can you try the cpanm command I have put, and return the log ?

```
cpanm -v https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
```

or 

```
LANG=de_DE cpanm -v https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
```

**Comment by eserte** [comment]
```
$ LANG=de_DE /opt/perl-5.20.3/bin/cpanm -v https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
cpanm (App::cpanminus) 1.7039 on perl 5.020003 built for x86_64-linux
Work directory is /home/eserte/.cpanm/work/1447008560.14156
You have make /usr/bin/make
You have LWP 6.13
You have /bin/tar: tar (GNU tar) 1.26
Copyright © 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL Version 3 oder später <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie dürfen sie ändern und weiter verbreiten.
Es gibt KEINERLEI GARANTIE, so weit das Gesetz es erlaubt.

Geschrieben von John Gilmore und Jay Fenlason.
You have /usr/bin/unzip
Unpacking MooX-Options-4.020.tar.gz
!
! Can't write to /opt/perl-5.20.3/lib/site_perl/5.20.3 and /opt/perl-5.20.3/bin: Installing modules to /home/eserte/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /opt/perl-5.20.3/lib/site_perl/5.20.3 and /opt/perl-5.20.3/bin)
!   - Configure local::lib your existing local::lib in this shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz
Fetching https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz ... OK
MooX-Options-4.020/t
MooX-Options-4.020/t/mo.t
MooX-Options-4.020
MooX-Options-4.020/README
MooX-Options-4.020/Changes
MooX-Options-4.020/t/doc.t
MooX-Options-4.020/t/moo.t
MooX-Options-4.020/t/pod.t
MooX-Options-4.020/LICENSE
MooX-Options-4.020/dist.ini
MooX-Options-4.020/po
MooX-Options-4.020/po/de.po
MooX-Options-4.020/t/role.t
MooX-Options-4.020/META.yml
MooX-Options-4.020/MANIFEST
MooX-Options-4.020/Build.PL
MooX-Options-4.020/t/base.st
MooX-Options-4.020/t/moose.t
MooX-Options-4.020/t/order.t
MooX-Options-4.020/t/Test.pm
MooX-Options-4.020/META.json
MooX-Options-4.020/t/hidden.t
MooX-Options-4.020/t/spacer.t
MooX-Options-4.020/README.mkdn
MooX-Options-4.020/po/de_DE.po
MooX-Options-4.020/t/failure.t
MooX-Options-4.020/t/flavour.t
MooX-Options-4.020/coverage.txt
MooX-Options-4.020/t/doc-utf8.t
MooX-Options-4.020/t/moox-cmd.t
MooX-Options-4.020/t/isa_check.t
MooX-Options-4.020/t/no_option.t
MooX-Options-4.020/t/multi_role.t
MooX-Options-4.020/xt
MooX-Options-4.020/xt/perltidy.rc
MooX-Options-4.020/t/00-compile.t
MooX-Options-4.020/t/with_config.t
MooX-Options-4.020/t/usage_string.t
MooX-Options-4.020/xt/perlcritic.rc
MooX-Options-4.020/t/author-critic.t
MooX-Options-4.020/lib/MooX
MooX-Options-4.020/lib/MooX/Options.pm
MooX-Options-4.020/po/MooX-Options.pot
MooX-Options-4.020/t/namespace_clean.t
MooX-Options-4.020/t/option-of-option.t
MooX-Options-4.020/t/lib
MooX-Options-4.020/t/lib/MooXCmdTest.pm
MooX-Options-4.020/t/release-kwalitee.t
MooX-Options-4.020/etc
MooX-Options-4.020/etc/with_config.t.json
MooX-Options-4.020/t/000-report-versions.t
MooX-Options-4.020/t/release-unused-vars.t
MooX-Options-4.020/t/author-pod-coverage.t
MooX-Options-4.020/etc/with_config_2.t.json
MooX-Options-4.020/lib/MooX/Options
MooX-Options-4.020/lib/MooX/Options/Role.pm
MooX-Options-4.020/t/around_options_usage.t
MooX-Options-4.020/t/check_target_methods.t
MooX-Options-4.020/t/multiple-split-options.t
MooX-Options-4.020/t/string_with_zero_value.t
MooX-Options-4.020/t/lib/TestNamespaceClean.pm
MooX-Options-4.020/t/lib/MooXCmdTest/Cmd
MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1.pm
MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test3.pm
MooX-Options-4.020/lib/MooX/Options/Descriptive.pm
MooX-Options-4.020/lib/MooX/Options/Manual
MooX-Options-4.020/lib/MooX/Options/Manual/Man.pod
MooX-Options-4.020/lib/MooX/Options/Manual/MooXCmd.pod
MooX-Options-4.020/lib/MooX/Options/Descriptive
MooX-Options-4.020/lib/MooX/Options/Descriptive/Usage.pm
MooX-Options-4.020/t/autosplit_warning_on_required_param.t
MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1/Cmd
MooX-Options-4.020/t/lib/MooXCmdTest/Cmd/test1/Cmd/test2.pm
MooX-Options-4.020/lib/MooX/Options/Manual/NamespaceClean.pod
MooX-Options-4.020/share/LocaleData/de/LC_MESSAGES
MooX-Options-4.020/share/LocaleData/de/LC_MESSAGES/MooX-Options.mo
MooX-Options-4.020/share/LocaleData/de_DE/LC_MESSAGES
MooX-Options-4.020/share/LocaleData/de_DE/LC_MESSAGES/MooX-Options.mo
Entering MooX-Options-4.020
Checking configure dependencies from META.json
Checking if you have Module::Build 0.4211 ... Yes (0.4214)
Checking if you have ExtUtils::Install 1.46 ... Yes (1.67)
Running Build.PL
Configuring MooX-Options-4.020 ... Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'MooX-Options' version '4.020'
Checking dependencies from MYMETA.json ...
Checking if you have English 0 ... Yes (1.09)
Checking if you have namespace::clean 0 ... Yes (0.25)
Checking if you have Term::Size::Any 0 ... Yes (0.002)
Checking if you have Role::Tiny::With 0 ... Yes (2.000001)
Checking if you have parent 0 ... Yes (0.234)
Checking if you have feature 0 ... Yes (1.36_01)
Checking if you have Text::LineFold 0 ... Yes (2012.04)
Checking if you have warnings 0 ... Yes (1.23)
Checking if you have Moo 1.003001 ... Yes (2.000002)
Checking if you have Module::Metadata 1.000019 ... Yes (1.000027)
Checking if you have File::ShareDir 1.00 ... Yes (1.102)
Checking if you have JSON::MaybeXS 0 ... Yes (1.003005)
Checking if you have Regexp::Common 0 ... Yes (2013031301)
Checking if you have IPC::Open3 0 ... Yes (1.16)
Checking if you have strict 0 ... Yes (1.08)
Checking if you have IO::Handle 0 ... Yes (1.35)
Checking if you have Pod::Usage 0 ... Yes (1.67)
Checking if you have Scalar::Util 0 ... Yes (1.42)
Checking if you have Module::Build 0.4211 ... Yes (0.4214)
Checking if you have overload 0 ... Yes (1.22)
Checking if you have Test::More 0.94 ... Yes (1.001014)
Checking if you have Locale::TextDomain 0 ... Yes (1.24)
Checking if you have File::Spec 0 ... Yes (3.48_01)
Checking if you have Try::Tiny 0 ... Yes (0.22)
Checking if you have Carp 0 ... Yes (1.36)
Checking if you have lib 0 ... Yes (0.63)
Checking if you have Data::Record 0 ... Yes (0.02)
Checking if you have Test::Requires 0 ... Yes (0.10)
Checking if you have MooX::ConfigFromFile 0 ... Yes (0.007)
Checking if you have blib 1.01 ... Yes (1.06)
Checking if you have Import::Into 0 ... Yes (1.002005)
Checking if you have FindBin 0 ... Yes (1.51)
Checking if you have Path::Class 0.32 ... Yes (0.35)
Checking if you have Capture::Tiny 0 ... Yes (0.30)
Checking if you have Test::Trap 0 ... Yes (0.3.2)
Checking if you have Getopt::Long 2.43 ... Yes (2.47)
Checking if you have Getopt::Long::Descriptive 0.099 ... Yes (0.099)
OK
Building and testing MooX-Options-4.020 ... Building MooX-Options
t/00-compile.t ........................... ok
# Testing with Perl 5.020003, /bbbike/perl-5.20.3/bin/perl
#     Capture::Tiny version is 0.30
#     Carp version is 1.36
#     Data::Record version is 0.02
#     English version is 1.09
#     File::Spec version is 3.48_01
#     FindBin version is 1.51
#     Getopt::Long version is 2.47
#     Getopt::Long::Descriptive version is 0.099
#     IO::Handle version is 1.35
#     IPC::Open3 version is 1.16
#     Import::Into version is 1.002005
#     JSON::MaybeXS version is 1.003005
#     Locale::TextDomain version is 1.24
#     Module::Build version is 0.4214
#     Module::Metadata version is 1.000027
#     Moo version is 2.000002
#     MooX::ConfigFromFile version is 0.007
#     Path::Class version is 0.35
#     Pod::Usage version is 1.67
#     Regexp::Common version is 2013031301
#     Role::Tiny::With version is 2.000001
#     Scalar::Util version is 1.42
#     Term::Size::Any version is 0.002
#     Test::More version is 1.001014
#     Test::Requires version is 0.10
#     Test::Trap version is 0.3.2
#     Text::LineFold version is 2012.04
#     Try::Tiny version is 0.22
#     blib version is 1.06
#     feature version is 1.36_01
#     lib version is 0.63
#     namespace::clean version is 0.25
#     overload version is 1.22
#     parent version is 0.234
#     strict version is 1.08
#     warnings version is 1.23
t/000-report-versions.t .................. ok

#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 46.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'

#   Failed test 'Usage ok'
#   at t/around_options_usage.t line 52.
#                   'Aufruf: around_options_usage.t [-ht] [long options...]'
#     doesn't match '(?^:^USAGE)'
# Looks like you failed 2 tests of 6.
t/around_options_usage.t ................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/6 subtests 
t/author-critic.t ........................ skipped: these tests are for testing by the author
t/author-pod-coverage.t .................. skipped: these tests are for testing by the author
t/autosplit_warning_on_required_param.t .. ok
t/check_target_methods.t ................. ok
t/doc-utf8.t ............................. ok
t/doc.t .................................. ok

#   Failed test 'negativable and format are incompatible'
#   at t/failure.t line 29.
#                   'Ungültige Formatspezifikation. Negierbare Parameter sind mit Bool'schen Werten nicht einsetzbar. at (eval 8) line 5.
# '
#     doesn't match '(?^x:^Negativable\sparams\sis\snot\susable\swith\snon\sboolean\svalue,\sdon't\spass\sformat\sto\suse\sit\s\!)'

#   Failed test 'help method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'help' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 49) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'help',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'man method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'man' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 60) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'man',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'usage method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'usage' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 71) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'usage',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'option method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'option' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 82) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'option',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'new_with_options method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'new_with_options' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 93) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'new_with_options',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'parse_options method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'parse_options' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 104) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'parse_options',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'options_usage method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen 'options_usage' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 115) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'options_usage',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test '_options_data method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen '_options_data' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 126) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'_options_data',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test '_options_config method can't be defined'
#   at t/failure.t line 47.
#                   'Sie können eine Option mit Namen '_options_config' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 137) line 5.
# '
#     doesn't match '(?^x:^You\scannot\suse\san\soption\swith\sthe\sname\s'_options_config',\sit\sis\simplied\sby\sMooX::Options)'

#   Failed test 'missing with'
#   at t/failure.t line 99.
#                   'Kann die Methode <with> nicht in <MissingWith> finden! Stellen Sie sicher, dass ein Role::Tiny kompatibles Modul, wie Moo oder Moose geladen ist, bevor Sie MooX::Options benutzen. at (eval 153) line 3.
# BEGIN failed--compilation aborted at (eval 153) line 3.
# '
#     doesn't match '(?^:^Can\'t\ find\ the\ method\ \<with\>\ in\ \<MissingWith\>\ \!\ Ensure\ to\ load\ a\ Role\:\:Tiny\ compatible\ module\ like\ Moo\ or\ Moose\ before\ using\ MooX\:\:Options\.)'

#   Failed test 'missing with'
#   at t/failure.t line 114.
#                   'Kann die Methode <around> nicht in <MissingAround> finden! Stellen Sie sicher, dass ein Role::Tiny kompatibles Modul, wie Moo oder Moose geladen ist, bevor Sie MooX::Options benutzen. at (eval 155) line 4.
# BEGIN failed--compilation aborted at (eval 155) line 4.
# '
#     doesn't match '(?^:^Can\'t\ find\ the\ method\ \<around\>\ in\ \<MissingAround\>\ \!\ Ensure\ to\ load\ a\ Role\:\:Tiny\ compatible\ module\ like\ Moo\ or\ Moose\ before\ using\ MooX\:\:Options\.)'

#   Failed test 'missing with'
#   at t/failure.t line 130.
#                   'Kann die Methode <has> nicht in <MissingHas> finden! Stellen Sie sicher, dass ein Role::Tiny kompatibles Modul, wie Moo oder Moose geladen ist, bevor Sie MooX::Options benutzen. at (eval 157) line 5.
# BEGIN failed--compilation aborted at (eval 157) line 5.
# '
#     doesn't match '(?^:^Can\'t\ find\ the\ method\ \<has\>\ in\ \<MissingHas\>\ \!\ Ensure\ to\ load\ a\ Role\:\:Tiny\ compatible\ module\ like\ Moo\ or\ Moose\ before\ using\ MooX\:\:Options\.)'
# Looks like you failed 13 tests of 16.
t/failure.t .............................. 
Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 13/16 subtests 
    
    #   Failed test 'died with usage message'
    #   at t/flavour.t line 74.
    #                   'Unknown option: unknown_option
    # Aufruf: flavour.t [-h] [long options...]
    # 
    #     --bool   no doc for bool
    #                                                                       
    #     --usage  Zeige einen kurzen Hilfetext
    #     -h       show a compact help message
    #     --help   show a long help message
    #     --man    Zeige das Handbuch
    # 
    # '
    #     doesn't match '(?^:USAGE:)'
    # Looks like you failed 1 test of 6.

#   Failed test 'unknown option plain'
#   at t/flavour.t line 76.
    
    #   Failed test 'died with usage message'
    #   at t/flavour.t line 74.
    #                   'Unknown option: unknown_option
    # Aufruf: flavour.t [-h] [long options...]
    # 
    #     --bool   no doc for bool
    #                                                                       
    #     --usage  Zeige einen kurzen Hilfetext
    #     -h       show a compact help message
    #     --help   show a long help message
    #     --man    Zeige das Handbuch
    # 
    # '
    #     doesn't match '(?^:USAGE:)'
    # Looks like you failed 1 test of 6.

#   Failed test 'unknown option plain2'
#   at t/flavour.t line 76.
# Looks like you failed 2 tests of 3.
t/flavour.t .............................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 
t/hidden.t ............................... ok

#   Failed test 'stderr ok'
#   at t/isa_check.t line 35.
#                   'boop
# Aufruf: isa_check.t [-h] [long options...]
# 
#     --hero=[Zeichenketten]  this is mandatory
#                                                                         
#     --usage                 Zeige einen kurzen Hilfetext
#     -h                      show a compact help message
#     --help                  show a long help message
#     --man                   Zeige das Handbuch
# 
# '
#     doesn't match '(?^:USAGE)'
# Looks like you failed 1 test of 2.
t/isa_check.t ............................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
        
        #   Failed test 'usage message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 126.
        #                   'USAGE: mo.t [ --str_req=Zeichenkette ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-str_req\=String\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 3.
    
    #   Failed test 'test short help'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 131.
        
        #   Failed test 'attr no doc is present'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 271.
        #                   'usage work
        # usage really work
        # Aufruf: mo.t [-h] [long options...]
        # 
        #     --split_conflict_str1=[Zeichenketten]  no doc for split_conflict_str1
        #     --split_conflict_str2=[Zeichenketten]  no doc for split_conflict_str2
        #     --split_str=[Zeichenketten]            no doc for split_str
        #                                                                       
        #     --usage                                Zeige einen kurzen Hilfetext
        #     -h                                     show a compact help message
        #     --help                                 show a long help message
        #     --man                                  Zeige das Handbuch
        # 
        # '
        #     doesn't match '(?^:split_str=\[Strings\]\s+no doc for split_str)'
        # Looks like you failed 1 test of 5.
    
    #   Failed test 'test usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 276.
        
        #   Failed test 'short message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 284.
        #                   'USAGE: mo.t [ --split_conflict_str1=[Zeichenketten] ] [ --split_conflict_str2=[Zeichenketten] ] [ --split_str=[Zeichenketten] ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-split_conflict_str1\=\[Strings\]\ \]\ \[\ \-\-split_conflict_str2\=\[Strings\]\ \]\ \[\ \-\-split_str\=\[Strings\]\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 2.
    
    #   Failed test 'test short usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 287.
    # Looks like you failed 3 tests of 24.

#   Failed test 'Mo'
#   at t/mo.t line 345.
# Looks like you failed 1 test of 1.
t/mo.t ................................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
        
        #   Failed test 'usage message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 126.
        #                   'USAGE: moo.t [ --str_req=Zeichenkette ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-str_req\=String\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 3.
    
    #   Failed test 'test short help'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 131.
        
        #   Failed test 'attr no doc is present'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 271.
        #                   'usage work
        # usage really work
        # Aufruf: moo.t [-h] [long options...]
        # 
        #     --split_conflict_str1=[Zeichenketten]  no doc for split_conflict_str1
        #     --split_conflict_str2=[Zeichenketten]  no doc for split_conflict_str2
        #     --split_str=[Zeichenketten]            no doc for split_str
        #                                                                       
        #     --usage                                Zeige einen kurzen Hilfetext
        #     -h                                     show a compact help message
        #     --help                                 show a long help message
        #     --man                                  Zeige das Handbuch
        # 
        # '
        #     doesn't match '(?^:split_str=\[Strings\]\s+no doc for split_str)'
        # Looks like you failed 1 test of 5.
    
    #   Failed test 'test usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 276.
        
        #   Failed test 'short message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 284.
        #                   'USAGE: moo.t [ --split_conflict_str1=[Zeichenketten] ] [ --split_conflict_str2=[Zeichenketten] ] [ --split_str=[Zeichenketten] ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-split_conflict_str1\=\[Strings\]\ \]\ \[\ \-\-split_conflict_str2\=\[Strings\]\ \]\ \[\ \-\-split_str\=\[Strings\]\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 2.
    
    #   Failed test 'test short usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 287.
    # Looks like you failed 3 tests of 24.

#   Failed test 'Moo'
#   at t/moo.t line 190.
# Looks like you failed 1 test of 1.
t/moo.t .................................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
        
        #   Failed test 'usage message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 126.
        #                   'USAGE: moose.t [ --str_req=Zeichenkette ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-str_req\=String\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 3.
    
    #   Failed test 'test short help'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 131.
        
        #   Failed test 'attr no doc is present'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 271.
        #                   'usage work
        # usage really work
        # Aufruf: moose.t [-h] [long options...]
        # 
        #     --split_conflict_str1=[Zeichenketten]  no doc for split_conflict_str1
        #     --split_conflict_str2=[Zeichenketten]  no doc for split_conflict_str2
        #     --split_str=[Zeichenketten]            no doc for split_str
        #                                                                       
        #     --usage                                Zeige einen kurzen Hilfetext
        #     -h                                     show a compact help message
        #     --help                                 show a long help message
        #     --man                                  Zeige das Handbuch
        # 
        # '
        #     doesn't match '(?^:split_str=\[Strings\]\s+no doc for split_str)'
        # Looks like you failed 1 test of 5.
    
    #   Failed test 'test usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 276.
        
        #   Failed test 'short message ok'
        #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 284.
        #                   'USAGE: moose.t [ --split_conflict_str1=[Zeichenketten] ] [ --split_conflict_str2=[Zeichenketten] ] [ --split_str=[Zeichenketten] ]  |  [ --usage ] [ -h ] [ --help ] [ --man ]
        # '
        #     doesn't match '(?^:USAGE\:\ m\w+\.t\ \[\ \-\-split_conflict_str1\=\[Strings\]\ \]\ \[\ \-\-split_conflict_str2\=\[Strings\]\ \]\ \[\ \-\-split_str\=\[Strings\]\ \]\ \ \|\ \ \[\ \-\-usage\ \]\ \[\ \-h\ \]\ \[\ \-\-help\ \]\ \[\ \-\-man\ \])'
        # Looks like you failed 1 test of 2.
    
    #   Failed test 'test short usage'
    #   at /home/eserte/.cpanm/work/1447008560.14156/MooX-Options-4.020/t/base.st line 287.
    # Looks like you failed 3 tests of 24.

#   Failed test 'Moose'
#   at t/moose.t line 199.
# Looks like you failed 1 test of 1.
t/moose.t ................................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

#   Failed test 'base command help ok'
#   at t/moox-cmd.t line 32.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'sub base command help ok'
#   at t/moox-cmd.t line 33.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:SUB\ COMMANDS\ AVAILABLE\:\ test1\,\ test3)'

#   Failed test 'pod synopsis ok'
#   at t/moox-cmd.t line 43.
#                   'NAME
#     moox-cmd.t
# 
# DESCRIPTION
#     This is a test sub command
# 
# SYNOPSIS
#     moox-cmd.t [-h] [Langoptionen ...]
# 
#     This is a test synopsis
# 
# OPTIONS
# 
# 
#     --usage:
#         Zeige einen kurzen Hilfetext
# 
#     -h: show a compact help message
# 
#     --help:
#         show a long help message
# 
#     --man:
#         Zeige das Handbuch
# 
# AVAILABLE SUB COMMANDS
#     test1 :
#         moox-cmd.t test1 [-h] [Langoptionen ...]
# 
#     test3 :
#         moox-cmd.t test3 [-h] [Langoptionen ...]
# 
# AUTHORS
#     Celogeek <me@celogeek.com>
# 
# '
#     doesn't match '(?^:SYNOPSIS\s+moox\-cmd\.t\ \[\-h\]\ \[long\ options\ \.\.\.\]\s+This\ is\ a\ test\ synopsis)'

#   Failed test 'subcommand 1 help ok'
#   at t/moox-cmd.t line 54.
#                   'Aufruf: moox-cmd.t test1 [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test2
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ test1\ \[\-h\])'

#   Failed test 'sub subcommand 1 help ok'
#   at t/moox-cmd.t line 56.
#                   'Aufruf: moox-cmd.t test1 [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test2
# 
# '
#     doesn't match '(?^:SUB\ COMMANDS\ AVAILABLE\:\ test2)'

#   Failed test 'no subcommand pass'
#   at t/moox-cmd.t line 64.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'no ref params'
#   at t/moox-cmd.t line 71.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'bad ref'
#   at t/moox-cmd.t line 78.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'bad ref'
#   at t/moox-cmd.t line 86.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'no command_name filled'
#   at t/moox-cmd.t line 94.
#                   'Aufruf: moox-cmd.t [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: test1, test3
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ \[\-h\])'

#   Failed test 'subcommand with mySub name'
#   at t/moox-cmd.t line 105.
#                   'Aufruf: moox-cmd.t mySub [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: a, b
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ mySub\ \[\-h\])'

#   Failed test 'sub subcommand with mySub name'
#   at t/moox-cmd.t line 107.
#                   'Aufruf: moox-cmd.t mySub [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# 
# Verfügbare Unterkommandos: a, b
# 
# '
#     doesn't match '(?^:SUB\ COMMANDS\ AVAILABLE\:\ a\,\ b)'

#   Failed test 'subcommand 2 ok'
#   at t/moox-cmd.t line 115.
#                   'Aufruf: moox-cmd.t test1 test2 [-h] [long options...]
# 
#                                                                         
#     --usage  Zeige einen kurzen Hilfetext
#     -h       show a compact help message
#     --help   show a long help message
#     --man    Zeige das Handbuch
# 
# '
#     doesn't match '(?^:USAGE\:\ moox\-cmd\.t\ test1\ test2\ \[\-h\])'
# Looks like you failed 13 tests of 16.
t/moox-cmd.t ............................. 
Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 13/16 subtests 
t/multi_role.t ........................... ok
t/multiple-split-options.t ............... ok
t/namespace_clean.t ...................... ok
t/no_option.t ............................ ok
t/option-of-option.t ..................... ok
t/order.t ................................ ok
t/pod.t .................................. skipped: these tests are for release candidate testing
t/release-kwalitee.t ..................... skipped: these tests are for release candidate testing
t/release-unused-vars.t .................. skipped: these tests are for release candidate testing
t/role.t ................................. ok
t/spacer.t ............................... ok
t/string_with_zero_value.t ............... ok
t/usage_string.t ......................... ok

#   Failed test 'error when try to include with_config_from_file into a role'
#   at t/with_config.t line 67.
#                   'Bitte, komponieren Sie die Option <with_config_from_file> nicht in eine Rolle. at (eval 110) line 3.
# BEGIN failed--compilation aborted at (eval 110) line 3.
# '
#     doesn't match '(?^x:Please\,\ don\'t\ use\ the\ option\ \<with_config_from_file\>\ into\ a\ role\.)'

#   Failed test 'keywords when we use config is bannish'
#   at t/with_config.t line 83.
#                   'Sie können eine Option mit Namen 'config_files' nicht einsetzen, da diese bereits von MooX::Options impliziert wird. at (eval 112) line 7.
# '
#     doesn't match '(?^x:You\ cannot\ use\ an\ option\ with\ the\ name\ \'config_files\'\,\ it\ is\ implied\ by\ MooX\:\:Options)'
# Looks like you failed 2 tests of 14.
t/with_config.t .......................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/14 subtests 

Test Summary Report
-------------------
t/around_options_usage.t               (Wstat: 512 Tests: 6 Failed: 2)
  Failed tests:  2, 5
  Non-zero exit status: 2
t/failure.t                            (Wstat: 3328 Tests: 16 Failed: 13)
  Failed tests:  1-10, 14-16
  Non-zero exit status: 13
t/flavour.t                            (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
t/isa_check.t                          (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/mo.t                                 (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/moo.t                                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/moose.t                              (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/moox-cmd.t                           (Wstat: 3328 Tests: 16 Failed: 13)
  Failed tests:  1-2, 5, 7-16
  Non-zero exit status: 13
t/with_config.t                        (Wstat: 512 Tests: 14 Failed: 2)
  Failed tests:  12-13
  Non-zero exit status: 2
Files=31, Tests=156,  4 wallclock secs ( 0.10 usr  0.19 sys +  3.63 cusr  0.68 csys =  4.60 CPU)
Result: FAIL
Failed 9/31 test programs. 36/156 subtests failed.
! Installing https://cpan.metacpan.org/authors/id/C/CE/CELOGEEK/MooX-Options-4.020.tar.gz failed. See /home/eserte/.cpanm/work/1447008560.14156/build.log for details. Retry with --force to force install it.
FAIL

```

**Comment by celogeek** [comment]
Um, I need a debian to check. Installing vagrant ...

**Comment by celogeek** [comment]
Ok I've go the problem on linux. Not on mac or BSD.

I will try to figure out what the problem is. If you got an idea on how to fix it, you are welcome ;)

**Comment by celogeek** [comment]
Oh god, it was the 4.019. this 4.020 is not yet on mirror. I check direct link

**Comment by celogeek** [comment]
find something ! if I use setlocale in POSIX, it works. I try on other platform.

**Comment by celogeek** [comment]
it should be fixed in 4.021 !

I have test on Mac and Linux. Mac and BSD need the ENV because setlocale has no effect. And Linux need setlocale ... I have put both.

Hope it is ok now.
